// Generated by Futhark 0.25.8
// git: f7fab79b80b4dfc86ce841f9dde6da42d53b2b84
#pragma once


// Headers
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <float.h>

#ifdef __cplusplus
extern "C" {
#endif

// Initialisation
struct futhark_context_config;
struct futhark_context_config *futhark_context_config_new(void);
void futhark_context_config_free(struct futhark_context_config *cfg);
int futhark_context_config_set_tuning_param(struct futhark_context_config *cfg, const char *param_name, size_t new_value);
struct futhark_context;
struct futhark_context *futhark_context_new(struct futhark_context_config *cfg);
void futhark_context_free(struct futhark_context *cfg);
void futhark_context_config_set_num_threads(struct futhark_context_config *cfg, int n);
void futhark_context_config_set_debugging(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_profiling(struct futhark_context_config *cfg, int flag);
void futhark_context_config_set_logging(struct futhark_context_config *cfg, int flag);
int futhark_get_tuning_param_count(void);
const char *futhark_get_tuning_param_name(int);
const char *futhark_get_tuning_param_class(int);

// Arrays
struct futhark_i8_2d;
struct futhark_i8_2d *futhark_new_i8_2d(struct futhark_context *ctx, const int8_t *data, int64_t dim0, int64_t dim1);
struct futhark_i8_2d *futhark_new_raw_i8_2d(struct futhark_context *ctx, unsigned char *data, int64_t offset, int64_t dim0, int64_t dim1);
int futhark_free_i8_2d(struct futhark_context *ctx, struct futhark_i8_2d *arr);
int futhark_values_i8_2d(struct futhark_context *ctx, struct futhark_i8_2d *arr, int8_t *data);
unsigned char *futhark_values_raw_i8_2d(struct futhark_context *ctx, struct futhark_i8_2d *arr);
const int64_t *futhark_shape_i8_2d(struct futhark_context *ctx, struct futhark_i8_2d *arr);

// Opaque values
struct futhark_opaque_c9ea81aa1ce9ad6ade9e4551313d2fb5;
struct futhark_opaque_state;
int futhark_free_opaque_c9ea81aa1ce9ad6ade9e4551313d2fb5(struct futhark_context *ctx, struct futhark_opaque_c9ea81aa1ce9ad6ade9e4551313d2fb5 *obj);
int futhark_store_opaque_c9ea81aa1ce9ad6ade9e4551313d2fb5(struct futhark_context *ctx, const struct futhark_opaque_c9ea81aa1ce9ad6ade9e4551313d2fb5 *obj, void **p, size_t *n);
struct futhark_opaque_c9ea81aa1ce9ad6ade9e4551313d2fb5 *futhark_restore_opaque_c9ea81aa1ce9ad6ade9e4551313d2fb5(struct futhark_context *ctx, const void *p);
int futhark_free_opaque_state(struct futhark_context *ctx, struct futhark_opaque_state *obj);
int futhark_store_opaque_state(struct futhark_context *ctx, const struct futhark_opaque_state *obj, void **p, size_t *n);
struct futhark_opaque_state *futhark_restore_opaque_state(struct futhark_context *ctx, const void *p);
int futhark_project_opaque_state_cells(struct futhark_context *ctx, struct futhark_opaque_c9ea81aa1ce9ad6ade9e4551313d2fb5 **out, const struct futhark_opaque_state *obj);
int futhark_new_opaque_state(struct futhark_context *ctx, struct futhark_opaque_state **out, const struct futhark_opaque_c9ea81aa1ce9ad6ade9e4551313d2fb5 *f_cells);

// Entry points
int futhark_entry_main(struct futhark_context *ctx, struct futhark_i8_2d **out0, const float in0, const float in1, const int64_t in2, const int64_t in3, const int32_t in4);
int futhark_entry_tui_init(struct futhark_context *ctx, struct futhark_opaque_state **out0, const int32_t in0, const int64_t in1, const int64_t in2);
int futhark_entry_tui_render(struct futhark_context *ctx, struct futhark_i8_2d **out0, const struct futhark_opaque_state *in0);
int futhark_entry_tui_step(struct futhark_context *ctx, struct futhark_opaque_state **out0, const float in0, const float in1, const struct futhark_opaque_state *in2);

// Miscellaneous
int futhark_context_sync(struct futhark_context *ctx);
void futhark_context_config_set_cache_file(struct futhark_context_config *cfg, const char *f);
char *futhark_context_report(struct futhark_context *ctx);
char *futhark_context_get_error(struct futhark_context *ctx);
void futhark_context_set_logging_file(struct futhark_context *ctx, FILE *f);
void futhark_context_pause_profiling(struct futhark_context *ctx);
void futhark_context_unpause_profiling(struct futhark_context *ctx);
int futhark_context_clear_caches(struct futhark_context *ctx);
#define FUTHARK_BACKEND_multicore
#define FUTHARK_SUCCESS 0
#define FUTHARK_PROGRAM_ERROR 2
#define FUTHARK_OUT_OF_MEMORY 3

#ifdef __cplusplus
}
#endif
